In [2]:
import numpy as np
import pandas as pd
pd.options.display.max_columns=20 #DataFrameの表示の際に、最大20列まで表示
pd.options.display.max_rows=20     #DataFrameの表示の際に、最大20行まで表示
pd.options.display.max_colwidth=80 #1つのセルに表示される文字数を最大80文字に制限
np.set_printoptions(precision=4,suppress=True) #小数点以下4桁まで表示かつ非常に小さい数を指数表記(e-05 とか)にしない

In [3]:
float_data=pd.Series([1.2,-3.5,np.nan,0])

In [4]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [5]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [6]:
string_data=pd.Series(["aardvark",np.nan,None,"avocado"])

In [7]:
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [8]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [9]:
float_data=pd.Series([1,2,None],dtype="float64")

In [10]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [11]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [12]:
string_data.dropna()

0    aardvark
3     avocado
dtype: object

In [13]:
string_data.fillna(0)

0    aardvark
1           0
2           0
3     avocado
dtype: object

In [14]:
string_data.notna()

0     True
1    False
2    False
3     True
dtype: bool

In [15]:
data=pd.Series([1,np.nan,3.5,np.nan,7])

In [16]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [17]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [21]:
data=pd.DataFrame([[1.,6.5,3.],[1.,np.nan,np.nan],[np.nan,np.nan,np.nan],
[np.nan,6.5,3.]])

In [22]:
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [23]:
data.dropna()

     0    1    2
0  1.0  6.5  3.0

In [24]:
data.dropna(how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [25]:
data[4]=np.nan

In [26]:
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [27]:
data.dropna(axis="columns",how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [29]:
df=pd.DataFrame(np.random.standard_normal((7,3)))

In [30]:
df.iloc[:4,1]=np.nan

In [31]:
df.iloc[:2,2]=np.nan

In [32]:
df

          0         1         2
0  0.039293       NaN       NaN
1  0.182499       NaN       NaN
2  0.347050       NaN -0.576589
3  1.581261       NaN  0.909539
4  0.937671  1.270734  1.129365
5  1.351131 -0.396417 -2.068312
6 -0.653519  0.362324  0.389843

In [33]:
df.dropna()

          0         1         2
4  0.937671  1.270734  1.129365
5  1.351131 -0.396417 -2.068312
6 -0.653519  0.362324  0.389843

In [35]:
df.dropna(thresh=2)
#同じ行にthresh以上NAあったら行削除

          0         1         2
2  0.347050       NaN -0.576589
3  1.581261       NaN  0.909539
4  0.937671  1.270734  1.129365
5  1.351131 -0.396417 -2.068312
6 -0.653519  0.362324  0.389843

In [36]:
df.fillna(0)

          0         1         2
0  0.039293  0.000000  0.000000
1  0.182499  0.000000  0.000000
2  0.347050  0.000000 -0.576589
3  1.581261  0.000000  0.909539
4  0.937671  1.270734  1.129365
5  1.351131 -0.396417 -2.068312
6 -0.653519  0.362324  0.389843

In [37]:
df.fillna({1:0.5,2:0})

          0         1         2
0  0.039293  0.500000  0.000000
1  0.182499  0.500000  0.000000
2  0.347050  0.500000 -0.576589
3  1.581261  0.500000  0.909539
4  0.937671  1.270734  1.129365
5  1.351131 -0.396417 -2.068312
6 -0.653519  0.362324  0.389843

In [38]:
df=pd.DataFrame(np.random.standard_normal((6,3)))

In [39]:
df.iloc[2:,1]=np.nan

In [40]:
df.iloc[4:,2]=np.nan

In [41]:
df

          0         1         2
0  1.004899  0.930082  1.297550
1 -0.136526 -0.139751  0.747880
2 -0.570419       NaN  1.050746
3 -0.428558       NaN  0.077663
4  0.794866       NaN       NaN
5 -0.630653       NaN       NaN

In [43]:
df.ffill()

          0         1         2
0  1.004899  0.930082  1.297550
1 -0.136526 -0.139751  0.747880
2 -0.570419 -0.139751  1.050746
3 -0.428558 -0.139751  0.077663
4  0.794866 -0.139751  0.077663
5 -0.630653 -0.139751  0.077663

In [44]:
df.ffill(limit=2)

          0         1         2
0  1.004899  0.930082  1.297550
1 -0.136526 -0.139751  0.747880
2 -0.570419 -0.139751  1.050746
3 -0.428558 -0.139751  0.077663
4  0.794866       NaN  0.077663
5 -0.630653       NaN  0.077663

In [45]:
data=pd.Series([1,np.nan,3.5,np.nan,7])

In [46]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [47]:
data.fillna(value=0)

0    1.0
1    0.0
2    3.5
3    0.0
4    7.0
dtype: float64

In [48]:
df.ffill(axis="index")

          0         1         2
0  1.004899  0.930082  1.297550
1 -0.136526 -0.139751  0.747880
2 -0.570419 -0.139751  1.050746
3 -0.428558 -0.139751  0.077663
4  0.794866 -0.139751  0.077663
5 -0.630653 -0.139751  0.077663

In [49]:
df.ffill(axis="columns")

          0         1         2
0  1.004899  0.930082  1.297550
1 -0.136526 -0.139751  0.747880
2 -0.570419 -0.570419  1.050746
3 -0.428558 -0.428558  0.077663
4  0.794866  0.794866  0.794866
5 -0.630653 -0.630653 -0.630653

In [50]:
data=pd.DataFrame({"k1":["one","two"]*3+["two"],
                   "k2":[1,1,2,3,3,4,4]})

In [51]:
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [52]:
data.duplicated()
#重複した行がないかをbool値で返す

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [54]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [55]:
data["v1"]=range(7)

In [56]:
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [57]:
data.drop_duplicates(subset=["k1"])

    k1  k2  v1
0  one   1   0
1  two   1   1

In [58]:
data.drop_duplicates(["k1","k2"],keep="last")

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [59]:
data=pd.DataFrame({"food":["bacon","pulled pork","bacon","pastrami"
                           ,"corned beef","bacon","pastrami","honey ham","nova lox"],
                   "ounces":[4,3,12,6,7.5,8,3,5,6]})

In [61]:
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [62]:
meat_to_animal={
    "bacon":"pig",
    "pulled pork":"pig",
    "pastrami":"cow",
    "corned beef":"cow",
    "honey ham":"pig",
    "nova lox":"salmon"
}

In [63]:
data["animal"]=data["food"].map(meat_to_animal)

In [64]:
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [65]:
def get_animal(x):
    return meat_to_animal[x]

In [66]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [67]:
data=pd.Series([1.,-999.,2.,-999.,-1000.,3.])

In [68]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [69]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [70]:
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [71]:
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [72]:
data.replace({-999:np.nan,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [73]:
data=pd.DataFrame(np.arange(12).reshape((3,4)),
                 index=["Ohio","Colorado","New York"],
                 columns=["one","two","three","four"])

In [74]:
def transform(x):
    return x[:4].upper()

In [75]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [76]:
data.index=data.index.map(transform)

In [77]:
data

      one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [78]:
data.rename(index=str.title,columns=str.upper)

      ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [80]:
data.rename(index={"OHIO":"INDIANA"},
           columns={"three":"peekaboo"})

         one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [81]:
ages=[20,22,25,27,21,23,37,31,61,45,41,32]

In [82]:
bins=[18,25,35,60,100]

In [83]:
age_categories=pd.cut(ages,bins)

In [84]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [85]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [86]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [87]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [92]:
pd.Series(age_categories).value_counts()

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [93]:
pd.cut(ages,bins,right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [94]:
group_names=["Youth","YoungAdult","MiddleAged","Senior"]

In [96]:
pd.cut(ages,bins,labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [97]:
data=np.random.uniform(size=20)

In [99]:
pd.cut(data,4,precision=2)
#precisionで小数点以下二桁の精度に設定

[(0.75, 0.99], (0.011, 0.26], (0.26, 0.5], (0.26, 0.5], (0.011, 0.26], ..., (0.5, 0.75], (0.011, 0.26], (0.011, 0.26], (0.5, 0.75], (0.75, 0.99]]
Length: 20
Categories (4, interval[float64, right]): [(0.011, 0.26] < (0.26, 0.5] < (0.5, 0.75] < (0.75, 0.99]]

In [100]:
data=np.random.standard_normal(1000)

In [103]:
quartiles=pd.qcut(data,4,precision=2)
#qcutは分位点をもとにカットする

In [104]:
quartiles

[(-3.07, -0.62], (0.069, 0.73], (-3.07, -0.62], (-3.07, -0.62], (-0.62, 0.069], ..., (-0.62, 0.069], (-0.62, 0.069], (-0.62, 0.069], (-3.07, -0.62], (-0.62, 0.069]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.07, -0.62] < (-0.62, 0.069] < (0.069, 0.73] < (0.73, 3.34]]

In [106]:
pd.Series(quartiles).value_counts()

(-3.07, -0.62]    250
(-0.62, 0.069]    250
(0.069, 0.73]     250
(0.73, 3.34]      250
Name: count, dtype: int64

In [108]:
pd.qcut(data,[0,0.1,0.5,0.9,1.]).value_counts()

(-3.062, -1.215]    100
(-1.215, 0.0689]    400
(0.0689, 1.37]      400
(1.37, 3.338]       100
Name: count, dtype: int64

In [110]:
data=pd.DataFrame(np.random.standard_normal((1000,4)))

In [111]:
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.005993    -0.033421     0.000199    -0.042909
std       1.001493     0.995255     1.004126     1.003180
min      -2.936828    -3.171208    -3.026909    -2.899566
25%      -0.645903    -0.689840    -0.687143    -0.730868
50%      -0.037011    -0.027100    -0.039339    -0.037589
75%       0.677417     0.633186     0.680120     0.650865
max       3.296247     3.219151     3.427558     2.802170

In [112]:
col=data[2]

In [113]:
col[col.abs()>3]

75    -3.026909
147    3.016293
761    3.427558
766    3.420104
Name: 2, dtype: float64

In [114]:
data[(data.abs()>3).any(axis="columns")]

            0         1         2         3
75   0.027925 -0.620241 -3.026909 -1.208715
124 -0.494163 -3.171208 -0.219481  0.080824
147  0.276228 -1.089276  3.016293  1.130058
289  3.296247  0.868835  1.806300  0.334086
646 -2.031705  3.145657  1.347442 -0.267983
761  0.605049  1.544264  3.427558 -0.033424
766  0.043554 -0.282288  3.420104 -0.099007
860 -2.016957  3.219151  1.204970 -1.001878

In [115]:
data[data.abs()>3]=np.sign(data)*3

In [117]:
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.006290    -0.033615    -0.000638    -0.042909
std       1.000559     0.993580     1.001278     1.003180
min      -2.936828    -3.000000    -3.000000    -2.899566
25%      -0.645903    -0.689840    -0.687143    -0.730868
50%      -0.037011    -0.027100    -0.039339    -0.037589
75%       0.677417     0.633186     0.680120     0.650865
max       3.000000     3.000000     3.000000     2.802170

In [119]:
np.sign(data).head()

     0    1    2    3
0  1.0 -1.0 -1.0 -1.0
1  1.0  1.0 -1.0  1.0
2  1.0  1.0  1.0 -1.0
3 -1.0 -1.0 -1.0  1.0
4 -1.0  1.0 -1.0  1.0

In [121]:
df=pd.DataFrame(np.arange(35).reshape((5,7)))

In [122]:
df

    0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [123]:
sampler=np.random.permutation(5)

In [124]:
sampler

array([3, 1, 0, 2, 4], dtype=int32)

In [125]:
df.take(sampler)

    0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34

In [126]:
df.iloc[sampler]

    0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34

In [127]:
columns_sampler=np.random.permutation(7)

In [128]:
columns_sampler

array([1, 4, 5, 3, 2, 0, 6], dtype=int32)

In [129]:
df.take(columns_sampler,axis="columns")

    1   4   5   3   2   0   6
0   1   4   5   3   2   0   6
1   8  11  12  10   9   7  13
2  15  18  19  17  16  14  20
3  22  25  26  24  23  21  27
4  29  32  33  31  30  28  34

In [131]:
df.sample(n=3)
#非復元抽出で指定した数だけ抽出

    0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20

In [132]:
choices=pd.Series([5,7,-1,6,4])

In [135]:
choices.sample(n=10,replace=True)
#replace=Trueで復元抽選になる

0    5
1    7
4    4
3    6
0    5
0    5
3    6
4    4
2   -1
3    6
dtype: int64

In [136]:
df=pd.DataFrame({"key":["b","b","a","c","a","b"],
                 "data1":range(6)})

In [137]:
df

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [142]:
pd.get_dummies(df["key"]).astype(int)

   a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [139]:
dummies=pd.get_dummies(df["key"],prefix="key")

In [143]:
df_with_dummy=df[["data1"]].join(dummies).astype(int)

In [144]:
df_with_dummy

   data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [149]:
mnames=["movie_id","title","genres"]

In [150]:
movies=pd.read_table("movies.dat",sep=r"::",
                    header=None,names=mnames,engine="python")

In [151]:
movies[:10]

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [157]:
dummies=movies["genres"].str.get_dummies("|").astype(int)

In [158]:
dummies.iloc[:10,:6]

   Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [159]:
movies_windic=movies.join(dummies.add_prefix("Genre_"))

In [160]:
movies_windic.iloc[0]

movie_id                                     1
title                         Toy Story (1995)
genres             Animation|Children's|Comedy
Genre_Action                                 0
Genre_Adventure                              0
                              ...
Genre_Romance                                0
Genre_Sci-Fi                                 0
Genre_Thriller                               0
Genre_War                                    0
Genre_Western                                0
Name: 0, Length: 21, dtype: object

In [161]:
np.random.seed(12345)

In [162]:
values=np.random.uniform(size=10)

In [163]:
values

array([0.9296, 0.3164, 0.1839, 0.2046, 0.5677, 0.5955, 0.9645, 0.6532,
       0.7489, 0.6536])

In [164]:
bins=[0,0.2,0.4,0.6,0.8,1]

In [165]:
pd.get_dummies(pd.cut(values,bins))

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

In [166]:
s=pd.Series([1,2,3,None])

In [167]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [168]:
s.dtype

dtype('float64')

In [169]:
s=pd.Series([1,2,3,None],dtype=pd.Int64Dtype())

In [170]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [171]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [172]:
s.dtype

Int64Dtype()

In [173]:
s[3]

In [175]:
s[3] is pd.NA

True

In [176]:
s=pd.Series([1,2,3,None],dtype="Int64")

In [177]:
s=pd.Series(["one","two",None,"three"],dtype=pd.StringDtype())

In [178]:
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [179]:
df=pd.DataFrame({"A":[1,2,None,4],
                "B":["one","two","three",None],
                "C":[False,None,False,True]})

In [180]:
df

     A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [181]:
df["A"]=df["A"].astype("Int64")

In [182]:
df["B"]=df["B"].astype("string")

In [183]:
df["C"]=df["C"].astype("boolean")

In [184]:
df

      A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

In [185]:
#CategoricalDtype カテゴリデータ型 "category"
#DatetimeTZDtype タイムゾーン付き日時
#Float32Dtype ヌル許容の32ビット浮動小数点数型　64もある "Float32"
#Int8Dtype ヌル許容の８ビット符号あり整数型　16,32,64もある "Int8"
#UInt8Dtype ヌル許容の８ビット符号なし整数型　16,32,64もある "UInt8"

In [186]:
val="a,b, guido"

In [187]:
val.split(",")

['a', 'b', ' guido']

In [188]:
pieces=[x.strip() for x in val.split(",")]

In [189]:
pieces

['a', 'b', 'guido']

In [190]:
first,second,third=pieces

In [191]:
first+"::"+second+"::"+third

'a::b::guido'

In [192]:
"::".join(pieces)

'a::b::guido'

In [193]:
"guid" in val

True

In [195]:
val.index(",")
#ないとエラーはく

1

In [197]:
val.find("::")
#ないと-1を出力する

-1

In [198]:
val.count(",")

2

In [199]:
val.replace(",","::")

'a::b:: guido'

In [200]:
val.replace(",","")

'ab guido'

In [201]:
import re

In [202]:
text="foo   bar\t baz \tqux"

In [203]:
re.split(r"\s+",text)

['foo', 'bar', 'baz', 'qux']

In [204]:
regex=re.compile(r"\s+")

In [205]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [206]:
regex.findall(text)

['   ', '\t ', ' \t']

In [207]:
text="""Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern=r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

In [208]:
regex=re.compile(pattern,flags=re.IGNORECASE)

In [209]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [210]:
m=regex.search(text)

In [211]:
m

In [212]:
text[m.start():m.end()]

'dave@google.com'

In [213]:
print(regex.match(text))

None

In [214]:
print(regex.sub("REDACTED",text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED

In [215]:
pattern=r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [216]:
regex=re.compile(pattern,flags=re.IGNORECASE)
#IGNORECASEで大文字小文字無視

In [217]:
m=regex.match("wesm@bright.net")

In [218]:
m.groups()

('wesm', 'bright', 'net')

In [219]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [220]:
print(regex.sub(r"Username:\1,Domain:\2,Suffix:\3",text))

Dave Username:dave,Domain:google,Suffix:com
Steve Username:steve,Domain:gmail,Suffix:com
Rob Username:rob,Domain:gmail,Suffix:com
Ryan Username:ryan,Domain:yahoo,Suffix:com

In [221]:
data={"Dave":"dave@google.com","Steve":"steve@gmail.com",
     "Rob":"rob@gmail.com","Wes":np.nan}

In [222]:
data=pd.Series(data)

In [223]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [224]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [226]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [227]:
data_as_string_ext=data.astype("string")

In [228]:
data_as_string_ext

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [229]:
data_as_string_ext.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [230]:
pattern=r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [231]:
data.str.findall(pattern,flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [232]:
matches=data.str.findall(pattern,flags=re.IGNORECASE).str[0]

In [233]:
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [234]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [236]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [237]:
data.str.extract(pattern,flags=re.IGNORECASE)

           0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

In [238]:
values=pd.Series(["apple","orange","apple","apple"]*2)

In [239]:
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [240]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [242]:
pd.Series(values).value_counts()

apple     6
orange    2
Name: count, dtype: int64

In [243]:
values=pd.Series([0,1,0,0]*2)

In [244]:
dim=pd.Series(["apple","orange"])

In [245]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [246]:
dim

0     apple
1    orange
dtype: object

In [247]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [248]:
fruits=["apple","orange","apple","apple"]*2

In [249]:
N=len(fruits)

In [250]:
rng=np.random.default_rng(seed=12345)

In [253]:
df=pd.DataFrame({"fruit":fruits,
                "basket_id":np.arange(N),
                "count":rng.integers(3,15,size=N),
                "weight":rng.uniform(0,4,size=N)},
                columns=["basket_id","fruit","count","weight"])

In [254]:
df

   basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [255]:
fruit_cat=df["fruit"].astype("category")

In [256]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [257]:
c=fruit_cat.array

In [258]:
type(c)

pandas.core.arrays.categorical.Categorical

In [259]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [260]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [261]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [263]:
df["fruit"]=df["fruit"].astype("category")

In [264]:
df["fruit"]

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [265]:
my_categories=pd.Categorical(["foo","bar","baz","foo","bar"])

In [266]:
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [267]:
categories=["foo","bar","baz"]

In [268]:
codes=[0,1,2,0,0,1]

In [272]:
my_cats_2=pd.Categorical.from_codes(codes,categories)

In [273]:
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [274]:
ordered_cat=pd.Categorical.from_codes(codes,categories,ordered=True)

In [275]:
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [277]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [278]:
rng=np.random.default_rng(seed=12345)

In [279]:
draws=rng.standard_normal(1000)

In [280]:
draws[:5]

array([-1.4238,  1.2637, -0.8707, -0.2592, -0.0753])

In [281]:
bins=pd.qcut(draws,4)

In [282]:
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [283]:
bins=pd.qcut(draws,4,labels=["Q1","Q2","Q3","Q4"])

In [284]:
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [285]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [286]:
bins=pd.Series(bins,name="quartile")

In [289]:
result=(pd.Series(draws).groupby(bins,observed=False)
       .agg(["count","min","max"])
       .reset_index())

In [290]:
result

  quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [291]:
result["quartile"]

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [292]:
N=1_000_000

In [293]:
labels=pd.Series(["foo","bar","baz","qux"]*(N//4))

In [294]:
categories=labels.astype("category")

In [295]:
labels.memory_usage(deep=True)

52000132

In [296]:
categories.memory_usage(deep=True)

1000512

In [298]:
%time _ =labels.astype("category")

CPU times: total: 109 ms
Wall time: 98.8 ms

In [299]:
%timeit labels.value_counts()

105 ms ± 33 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [300]:
%timeit categories.value_counts()

10.3 ms ± 216 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [301]:
s=pd.Series(["a","b","c","d"]*2)

In [303]:
cat_s=s.astype("category")

In [304]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [305]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [306]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [307]:
actual_categories=["a","b","c","d","e"]

In [308]:
cat_s2=cat_s.cat.set_categories(actual_categories)

In [309]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [310]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [311]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [312]:
cat_s3=cat_s[cat_s.isin(["a","b"])]

In [313]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [314]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [315]:
cat_s=pd.Series(["a","b","c","d"]*2,dtype="category")

In [318]:
pd.get_dummies(cat_s).astype("int64")

   a  b  c  d
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  0  0  1
4  1  0  0  0
5  0  1  0  0
6  0  0  1  0
7  0  0  0  1