In [8]:
import numpy as np
import pandas as pd
pd.options.display.max_columns=20 #DataFrameの表示の際に、最大20列まで表示
pd.options.display.max_rows=20     #DataFrameの表示の際に、最大20行まで表示
pd.options.display.max_colwidth=80 #1つのセルに表示される文字数を最大80文字に制限
np.set_printoptions(precision=4,suppress=True) #小数点以下4桁まで表示かつ非常に小さい数を指数表記(e-05 とか)にしない

In [9]:
!type ex1.csv

a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [10]:
df=pd.read_csv("ex1.csv")

In [11]:
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [11]:
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [12]:
!type ex2.csv

1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [13]:
pd.read_csv("ex2.csv",header=None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [14]:
pd.read_csv("ex2.csv",names=["a","b","c","d","message"])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [15]:
names=["a","b","c","d","message"]

In [16]:
pd.read_csv("ex2.csv",names=names,index_col="message")

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [17]:
!type csv_mindex.csv

key1,key2,value1,value2
one,a,1,2
one,b,3,4
one,c,5,6
one,d,7,8
two,a,9,10
two,b,11,12
two,c,13,14
two,d,15,16

In [18]:
parsed=pd.read_csv("csv_mindex.csv",
                  index_col=["key1","key2"])

In [19]:
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [20]:
!type ex3.txt

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [23]:
result=pd.read_csv("ex3.txt",sep=r"\s+")
#\sは空白文字、+は一回以上の連続、r""はPythonのraw文字

In [22]:
result

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [24]:
!type ex4.csv

# hey!
a,b,c,d,message
# just wanted to make things more difficult for you
# who reads CSV files with computers, anyway?
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [26]:
pd.read_csv("ex4.csv",skiprows=[0,2,3])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [27]:
!type ex5.csv

something,a,b,c,d,message
one,1,2,3,4,NA
two,5,6,,8,world
three,9,10,11,12,foo

In [28]:
result=pd.read_csv("ex5.csv")

In [29]:
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [31]:
pd.isna(result)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [32]:
result=pd.read_csv("ex5.csv",na_values=["NULL"])

In [33]:
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [34]:
result2=pd.read_csv("ex5.csv",keep_default_na=False)

In [35]:
result2

  something  a   b   c   d message
0       one  1   2   3   4      NA
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [36]:
result2.isna()

   something      a      b      c      d  message
0      False  False  False  False  False    False
1      False  False  False  False  False    False
2      False  False  False  False  False    False

In [37]:
result3=pd.read_csv("ex5.csv",keep_default_na=False,
                   na_values=["NA"])

In [38]:
result3

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [39]:
result3.isna()

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False  False  False    False
2      False  False  False  False  False    False

In [40]:
sentinels={"message":["foo","NA"],"something":["two"]}

In [41]:
pd.read_csv("ex5.csv",na_values=sentinels,keep_default_na=False)

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       NaN  5   6       8   world
2     three  9  10  11  12     NaN

In [42]:
pd.options.display.max_rows=10

In [43]:
result=pd.read_csv("ex6.csv")

In [44]:
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [46]:
pd.read_csv("ex6.csv",nrows=5)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [47]:
chunker=pd.read_csv("ex6.csv",chunksize=1000)

In [48]:
type(chunker)

pandas.io.parsers.readers.TextFileReader

In [49]:
tot=pd.Series([],dtype='int64')

In [50]:
for piece in chunker:
    tot=tot.add(piece["key"].value_counts(),fill_value=0)

In [51]:
tot=tot.sort_values(ascending=False)

In [52]:
tot[:10]

key
E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
M    338.0
J    337.0
F    335.0
K    334.0
H    330.0
dtype: float64

In [53]:
data=pd.read_csv("ex5.csv")

In [54]:
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [60]:
data.to_csv("out.csv")
#out.csvというファイルを作ってそこに書き込み

In [61]:
!type out.csv

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

In [62]:
import sys

In [63]:
data.to_csv(sys.stdout,sep="|")
#sys.stdoutでただ出力するだけになる

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

In [64]:
data.to_csv(sys.stdout,index=False,header=False)

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

In [65]:
data.to_csv(sys.stdout,index=False,columns=["a","b","c"])

a,b,c
1,2,3.0
5,6,
9,10,11.0

In [66]:
!type ex7.csv

"a","b","c"
"1","2","3"
"1","2","3"

In [67]:
import csv

In [69]:
f=open("ex7.csv")

In [70]:
reader=csv.reader(f)

In [71]:
for line in reader:
    print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [72]:
f.close()

In [74]:
with open("ex7.csv") as f:
    lines=list(csv.reader(f))

In [75]:
header,values=lines[0],lines[1:]

In [76]:
data_dict={h:v for h,v in zip(header,zip(*values))}

In [77]:
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

In [78]:
import json

In [83]:
obj="""
{"name":"Wes",
"cities_lived":["Akron","Nashville","New York","San Francisco"],
"pet":null,
"siblings":[{"name":"Scott","age":34,"hobbies":["guitars","soccer"]},
{"name":"Katie","age":42,"hobbies":["diving","art"]}]
}
"""

In [84]:
import json

In [85]:
result=json.loads(obj)

In [86]:
result

{'name': 'Wes',
 'cities_lived': ['Akron', 'Nashville', 'New York', 'San Francisco'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 34, 'hobbies': ['guitars', 'soccer']},
  {'name': 'Katie', 'age': 42, 'hobbies': ['diving', 'art']}]}

In [87]:
asjson=json.dumps(result)

In [88]:
asjson

'{"name": "Wes", "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"], "pet": null, "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]}, {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]}'

In [89]:
siblings=pd.DataFrame(result["siblings"],columns=["name","age"])

In [90]:
siblings

    name  age
0  Scott   34
1  Katie   42

In [91]:
!type example.json

[{"a": 1, "b": 2, "c": 3},
 {"a": 4, "b": 5, "c": 6},
 {"a": 7, "b": 8, "c": 9}]

In [92]:
data=pd.read_json("example.json")

In [93]:
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [94]:
data.to_json(sys.stdout)

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}

In [96]:
data.to_json(sys.stdout,orient="records")
#orient="records"で、各行を辞書にして、それをリストにまとめる

[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

In [97]:
pip install lxml

Requirement already satisfied: lxml in c:\users\sansp\anaconda3\lib\site-packages (5.3.0)
Note: you may need to restart the kernel to use updated packages.

In [98]:
tables=pd.read_html("fdic_failed_bank_list.html")

In [99]:
len(tables)

1

In [100]:
failures=tables[0]

In [101]:
failures.head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"

In [102]:
close_timestamps=pd.to_datetime(failures["Closing Date"])

In [104]:
close_timestamps.dt.year.value_counts()

Closing Date
2010    157
2009    140
2011     92
2012     51
2008     25
       ...
2004      4
2001      4
2007      3
2003      3
2000      2
Name: count, Length: 15, dtype: int64

In [130]:
from lxml import objectify

In [131]:
path="Performance_MNR.xml"

In [132]:
with open(path) as f:
    parsed=objectify.parse(f)

In [133]:
root=parsed.getroot()

In [137]:
data=[]
skip_fields=["PARENT_SEQ","INDICATOR_SEQ","DESIRED_CHANGE","DECIMAL_PLACES"]
for elt in root.INDICATOR:
    el_data={}
    for child in elt.getchildren():
        if child.tag in skip_fields:
            continue
        el_data[child.tag]=child.pyval
    data.append(el_data)

In [138]:
perf=pd.DataFrame(data)

In [139]:
perf.head()

,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,INDICATOR_UNIT,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 minute...,2008,1,Service Indicators,M,%,95.0,96.9,95.0,96.9
1,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 minute...,2008,2,Service Indicators,M,%,95.0,96.0,95.0,95.0
2,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 minute...,2008,3,Service Indicators,M,%,95.0,96.3,95.0,96.9
3,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 minute...,2008,4,Service Indicators,M,%,95.0,96.8,95.0,98.3
4,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 minute...,2008,5,Service Indicators,M,%,95.0,96.6,95.0,95.8

In [140]:
perf2=pd.read_xml(path)

In [141]:
perf2.head()

,INDICATOR_SEQ,PARENT_SEQ,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,DESIRED_CHANGE,INDICATOR_UNIT,DECIMAL_PLACES,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 minute...,2008,1,Service Indicators,M,U,%,1,95.00,96.90,95.00,96.90
1,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 minute...,2008,2,Service Indicators,M,U,%,1,95.00,96.00,95.00,95.00
2,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 minute...,2008,3,Service Indicators,M,U,%,1,95.00,96.30,95.00,96.90
3,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 minute...,2008,4,Service Indicators,M,U,%,1,95.00,96.80,95.00,98.30
4,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 minute...,2008,5,Service Indicators,M,U,%,1,95.00,96.60,95.00,95.80

In [142]:
frame=pd.read_csv("ex1.csv")

In [143]:
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [144]:
frame.to_pickle("frame_pickle")

In [145]:
pd.read_pickle("frame_pickle")

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [146]:
fec=pd.read_parquet("fec.parquet")

In [147]:
fec.head()

,cmte_id,cand_id,cand_nm,contbr_nm,contbr_city,contbr_st,contbr_zip,contbr_employer,contbr_occupation,contb_receipt_amt,contb_receipt_dt,receipt_desc,memo_cd,memo_text,form_tp,file_num
0,C00410118,P20002978,"Bachmann, Michelle","HARVEY, WILLIAM",MOBILE,AL,366010290,RETIRED,RETIRED,250.0,20-JUN-11,None,None,None,SA17A,736166
1,C00410118,P20002978,"Bachmann, Michelle","HARVEY, WILLIAM",MOBILE,AL,366010290,RETIRED,RETIRED,50.0,23-JUN-11,None,None,None,SA17A,736166
2,C00410118,P20002978,"Bachmann, Michelle","SMITH, LANIER",LANETT,AL,368633403,INFORMATION REQUESTED,INFORMATION REQUESTED,250.0,05-JUL-11,None,None,None,SA17A,749073
3,C00410118,P20002978,"Bachmann, Michelle","BLEVINS, DARONDA",PIGGOTT,AR,724548253,NONE,RETIRED,250.0,01-AUG-11,None,None,None,SA17A,749073
4,C00410118,P20002978,"Bachmann, Michelle","WARDENBURG, HAROLD",HOT SPRINGS NATION,AR,719016467,NONE,RETIRED,300.0,20-JUN-11,None,None,None,SA17A,736166

In [148]:
fec.count()

cmte_id         1001731
cand_id         1001731
cand_nm         1001731
contbr_nm       1001731
contbr_city     1001712
                 ...
receipt_desc      14166
memo_cd           92482
memo_text         97770
form_tp         1001731
file_num        1001731
Length: 16, dtype: int64

In [149]:
pip install openpyxl xlrd

Requirement already satisfied: openpyxl in c:\users\sansp\anaconda3\lib\site-packages (3.1.5)
Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: et-xmlfile in c:\users\sansp\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2
Note: you may need to restart the kernel to use updated packages.

In [150]:
xlsx=pd.ExcelFile("ex1.xlsx")

In [151]:
xlsx.sheet_names

['Sheet1']

In [152]:
xlsx.parse(sheet_name="Sheet1")

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [153]:
xlsx.parse(sheet_names="Sheet1",index_col=0)

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [154]:
writer=pd.ExcelWriter("ex2.xlsx")

In [155]:
frame=pd.read_excel("ex1.xlsx",sheet_name="Sheet1")

In [159]:
frame.to_excel(writer,sheet_name="Sheet1")

In [160]:
writer.close()

In [161]:
frame.to_excel("ex2.xlsx")

In [163]:
frame=pd.DataFrame({"a":np.random.standard_normal(100)})

In [164]:
store=pd.HDFStore("mydata.h5")

In [165]:
store["obj1"]=frame

In [166]:
store["obj_col"]=frame["a"]

In [167]:
store

<class 'pandas.io.pytables.HDFStore'>
File path: mydata.h5

In [168]:
store["obj1"]

           a
0  -0.681756
1   1.005690
2   1.270770
3  -1.374928
4  -0.356797
..       ...
95 -0.647907
96 -1.186411
97  0.198105
98 -0.455634
99  0.935215

[100 rows x 1 columns]

In [169]:
store.put("obj2",frame,format="table")

In [170]:
store.select("obj2",where=["index>=10 and index<=15"])

           a
10 -0.546139
11 -0.549674
12 -0.699372
13 -0.732676
14  1.398694
15 -0.404669

In [171]:
store.close()

In [179]:
frame.to_hdf("mydata.h5",key="obj3",format="table")

In [180]:
pd.read_hdf("mydata.h5",key="obj3",where=["index<5"])

          a
0 -0.681756
1  1.005690
2  1.270770
3 -1.374928
4 -0.356797

In [181]:
import os

In [182]:
os.remove("mydata.h5")
#HDF5ファイルの削除

In [183]:
import requests

In [184]:
url="https://api.github.com/repos/pandas-dev/pandas/issues"

In [185]:
resp=requests.get(url)

In [186]:
resp.raise_for_status()

In [187]:
resp

In [188]:
data=resp.json()

In [189]:
data[0]["title"]

'BUG: eval not working with string containment'

In [192]:
issues=pd.DataFrame(data,columns=["number","title","labels","state"])

In [193]:
issues

,number,title,labels,state
0,64418,BUG: eval not working with string containment,[],open
1,64417,BUG: honor exclude in DataFrame.from_records with iterator nrows=0,[],open
2,64416,DOC: add gotcha about storing nested lists in object columns,[],open
3,64415,DOC: Narrow `read_csv` memory-leak note to regression scope and provide repr...,[],open
4,64412,DOC: fix dtype dict examples in read_csv/read_table,[],open
...,...,...,...,...
25,64365,TST: Use EA scalar instead of python scalar in `test_compare_scalar`,[],open
26,64363,PERF: datetime index getters functions are 10 times slower with ZoneInfo vs ...,"[{'id': 211840, 'node_id': 'MDU6TGFiZWwyMTE4NDA=', 'url': 'https://api.githu...",open
27,64347,WIP: parallelize read_csv,[],open
28,64346,DOC: use docs version for stable source links,[],open
29,64345,DISC: pd.option_context thread-safety,"[{'id': 34423912, 'node_id': 'MDU6TGFiZWwzNDQyMzkxMg==', 'url': 'https://api...",open

In [200]:
query="""
CREATE TABLE test
(a VARCHAR(20),b VARCHAR(20),
c REAL,d INTEGER
);"""
#VARCHAR(20)は最大20文字まで入る文字列　可変長で、例えば二文字だけ入れたら二文字として扱ってくれる

In [201]:
import sqlite3
con=sqlite3.connect("mydata.sqlite")

In [202]:
con.execute(query)

In [204]:
con.commit()
#これでconに加えられた変更が保存される

In [205]:
data=[("Atlanta","Georgia",1.25,6),
     ("Tallahassee","Florida",2.6,3),
     ("Sacramento","California",1.7,5)]

In [206]:
stmt="INSERT INTO test VALUES(?,?,?,?)"

In [207]:
con.executemany(stmt,data)

In [208]:
con.commit()

In [209]:
cursor=con.execute("SELECT * FROM test")

In [210]:
rows=cursor.fetchall()

In [211]:
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [212]:
cursor.description

(('a', None, None, None, None, None, None),
 ('b', None, None, None, None, None, None),
 ('c', None, None, None, None, None, None),
 ('d', None, None, None, None, None, None))

In [213]:
pd.DataFrame(rows,columns=[x[0] for x in cursor.description])

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [214]:
import sqlalchemy as sqla

In [217]:
db=sqla.create_engine("sqlite:///mydata.sqlite")

In [218]:
pd.read_sql("SELECT * FROM test",db)

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5