In [114]:
import numpy as np
import pandas as pd
pd.options.display.max_columns=20 #DataFrameの表示の際に、最大20列まで表示
pd.options.display.max_rows=20     #DataFrameの表示の際に、最大20行まで表示
pd.options.display.max_colwidth=80 #1つのセルに表示される文字数を最大80文字に制限
np.set_printoptions(precision=4,suppress=True) #小数点以下4桁まで表示かつ非常に小さい数を指数表記(e-05 とか)にしない

In [115]:
df=pd.DataFrame({"key1":["a","a",None,"b","b","a",None],
                "key2":pd.Series([1,2,1,2,1,None,1],dtype="Int64"),
                "data1":np.random.standard_normal(7),
                "data2":np.random.standard_normal(7)})

In [116]:
df

   key1  key2     data1     data2
0     a     1  0.679668 -0.899685
1     a     2 -1.380083 -0.394793
2  None     1  0.896494 -0.571336
3     b     2  0.013447  0.515783
4     b     1 -0.542326  0.220146
5     a  <NA>  1.649193  0.612402
6  None     1 -0.499942  0.253695

In [117]:
grouped=df["data1"].groupby(df["key1"])

In [118]:
grouped

In [119]:
grouped.mean()

key1
a    0.316259
b   -0.264440
Name: data1, dtype: float64

In [120]:
means=df["data1"].groupby([df["key1"],df["key2"]]).mean()

In [121]:
means

key1  key2
a     1       0.679668
      2      -1.380083
b     1      -0.542326
      2       0.013447
Name: data1, dtype: float64

In [122]:
means.unstack()

key2         1         2
key1
a     0.679668 -1.380083
b    -0.542326  0.013447

In [123]:
states=np.array(["OH","CA","CA","OH","OH","CA","OH"])

In [124]:
years=[2005,2005,2006,2005,2006,2005,2006]

In [125]:
df["data1"].groupby([states,years]).mean()

CA  2005    0.134555
    2006    0.896494
OH  2005    0.346557
    2006   -0.521134
Name: data1, dtype: float64

In [126]:
df.groupby("key1").mean()

      key2     data1     data2
key1
a      1.5  0.316259 -0.227359
b      1.5 -0.264440  0.367965

In [127]:
df.groupby("key2").mean(numeric_only=True)
#numeric_onlyで数値の行だけ計算

         data1     data2
key2
1     0.133473 -0.249295
2    -0.683318  0.060495

In [128]:
df.groupby(["key1","key2"]).mean()

              data1     data2
key1 key2
a    1     0.679668 -0.899685
     2    -1.380083 -0.394793
b    1    -0.542326  0.220146
     2     0.013447  0.515783

In [129]:
df.groupby(["key1","key2"]).size()

key1  key2
a     1       1
      2       1
b     1       1
      2       1
dtype: int64

In [130]:
df.groupby("key1",dropna=False).size()

key1
a      3
b      2
NaN    2
dtype: int64

In [131]:
df.groupby(["key1","key2"],dropna=False).size()

key1  key2
a     1       1
      2       1
      <NA>    1
b     1       1
      2       1
NaN   1       2
dtype: int64

In [132]:
df.groupby("key1").count()

      key2  data1  data2
key1
a        2      3      3
b        2      2      2

In [133]:
for name,group in df.groupby("key1"):
    print(name)
    print(group)

a
  key1  key2     data1     data2
0    a     1  0.679668 -0.899685
1    a     2 -1.380083 -0.394793
5    a  <NA>  1.649193  0.612402
b
  key1  key2     data1     data2
3    b     2  0.013447  0.515783
4    b     1 -0.542326  0.220146

In [134]:
for (k1,k2),group in df.groupby(["key1","key2"]):
    print((k1,k2))
    print(group)

('a', np.int64(1))
  key1  key2     data1     data2
0    a     1  0.679668 -0.899685
('a', np.int64(2))
  key1  key2     data1     data2
1    a     2 -1.380083 -0.394793
('b', np.int64(1))
  key1  key2     data1     data2
4    b     1 -0.542326  0.220146
('b', np.int64(2))
  key1  key2     data1     data2
3    b     2  0.013447  0.515783

In [135]:
pieces={name:group for name,group in df.groupby("key1") }

In [136]:
pieces["b"]

  key1  key2     data1     data2
3    b     2  0.013447  0.515783
4    b     1 -0.542326  0.220146

In [137]:
grouped=df.groupby({"key1":"key","key2":"key",
                    "data1":"data","data2":"data"},axis="columns")

C:\Users\sansp\AppData\Local\Temp\ipykernel_36516\361733129.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  grouped=df.groupby({"key1":"key","key2":"key",

In [138]:
for group_key,group_values in grouped:
    print(group_key)
    print(group_values)

data
      data1     data2
0  0.679668 -0.899685
1 -1.380083 -0.394793
2  0.896494 -0.571336
3  0.013447  0.515783
4 -0.542326  0.220146
5  1.649193  0.612402
6 -0.499942  0.253695
key
   key1  key2
0     a     1
1     a     2
2  None     1
3     b     2
4     b     1
5     a  <NA>
6  None     1

In [139]:
df.groupby(["key1","key2"])[["data2"]].mean()

              data2
key1 key2
a    1    -0.899685
     2    -0.394793
b    1     0.220146
     2     0.515783

In [140]:
s_grouped=df.groupby(["key1","key2"])["data2"]

In [141]:
s_grouped.mean()

key1  key2
a     1      -0.899685
      2      -0.394793
b     1       0.220146
      2       0.515783
Name: data2, dtype: float64

In [142]:
people=pd.DataFrame(np.random.standard_normal((5,5)),
                   columns=["a","b","c","d","e"],
                   index=["Joe","Steve","Wanda","Jill","Trey"])

In [143]:
people.iloc[2:3,[1,2]]=np.nan

In [144]:
people

              a         b         c         d         e
Joe    0.926850 -0.474480 -0.068073 -1.520311  0.464127
Steve -3.390809  1.006583 -0.720127 -0.131144  0.913703
Wanda  0.880057       NaN       NaN  1.055051 -1.046718
Jill  -0.616380 -1.587230  1.742940  1.694443 -0.125046
Trey  -1.557760 -0.905458 -0.083322 -2.441180 -1.693384

In [145]:
mapping={"a":"red","b":"red","c":"blue","d":"blue","e":"red","f":"orange"}

In [146]:
by_column=people.groupby(mapping,axis="columns")

C:\Users\sansp\AppData\Local\Temp\ipykernel_36516\2149570058.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  by_column=people.groupby(mapping,axis="columns")

In [147]:
by_column.sum()

           blue       red
Joe   -1.588384  0.916498
Steve -0.851272 -1.470523
Wanda  1.055051 -0.166661
Jill   3.437383 -2.328657
Trey  -2.524501 -4.156601

In [148]:
map_series=pd.Series(mapping)

In [149]:
map_series

a       red
b       red
c      blue
d      blue
e       red
f    orange
dtype: object

In [150]:
people.groupby(map_series,axis="columns").count()

C:\Users\sansp\AppData\Local\Temp\ipykernel_36516\172532021.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  people.groupby(map_series,axis="columns").count()

       blue  red
Joe       2    3
Steve     2    3
Wanda     1    2
Jill      2    3
Trey      2    3

In [151]:
people.groupby(len).sum()

          a         b         c         d         e
3  0.926850 -0.474480 -0.068073 -1.520311  0.464127
4 -2.174140 -2.492688  1.659618 -0.746737 -1.818430
5 -2.510752  1.006583 -0.720127  0.923906 -0.133015

In [152]:
key_list=["one","one","one","two","two"]

In [153]:
people.groupby([len,key_list]).min()

              a         b         c         d         e
3 one  0.926850 -0.474480 -0.068073 -1.520311  0.464127
4 two -1.557760 -1.587230 -0.083322 -2.441180 -1.693384
5 one -3.390809  1.006583 -0.720127 -0.131144 -1.046718

In [154]:
columns=pd.MultiIndex.from_arrays([["US","US","US","JP","JP"],
                                 [1,3,5,1,3]],names=["cty","tenor"])

In [155]:
hier_df=pd.DataFrame(np.random.standard_normal((4,5)),columns=columns)

In [156]:
hier_df

cty          US                            JP
tenor         1         3         5         1         3
0      1.183463 -1.303253 -1.003029 -0.729001 -2.029691
1      0.242627 -0.149149 -0.761951 -1.108089 -1.677632
2     -1.129957 -0.072889  0.693114  0.832597  0.162794
3      1.215446  0.817052 -0.042027  1.111295 -2.003878

In [157]:
hier_df.groupby(level="cty",axis="columns").count()

C:\Users\sansp\AppData\Local\Temp\ipykernel_36516\1991154737.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  hier_df.groupby(level="cty",axis="columns").count()

cty  JP  US
0     2   3
1     2   3
2     2   3
3     2   3

In [158]:
df

   key1  key2     data1     data2
0     a     1  0.679668 -0.899685
1     a     2 -1.380083 -0.394793
2  None     1  0.896494 -0.571336
3     b     2  0.013447  0.515783
4     b     1 -0.542326  0.220146
5     a  <NA>  1.649193  0.612402
6  None     1 -0.499942  0.253695

In [159]:
grouped=df.groupby("key1")

In [160]:
grouped["data1"].nsmallest(2)

key1
a     1   -1.380083
      0    0.679668
b     4   -0.542326
      3    0.013447
Name: data1, dtype: float64

In [161]:
def peak_to_peak(arr):
    return arr.max()-arr.min()

In [162]:
grouped.agg(peak_to_peak)

      key2     data1     data2
key1
a        1  3.029276  1.512087
b        1  0.555773  0.295638

In [163]:
grouped.describe()

      key2                                           data1            ...  \
     count mean       std  min   25%  50%   75%  max count      mean  ...
key1                                                                  ...
a      2.0  1.5  0.707107  1.0  1.25  1.5  1.75  2.0   3.0  0.316259  ...
b      2.0  1.5  0.707107  1.0  1.25  1.5  1.75  2.0   2.0 -0.264440  ...

                         data2                                          \
           75%       max count      mean       std       min       25%
key1
a     1.164431  1.649193   3.0 -0.227359  0.769823 -0.899685 -0.647239
b    -0.125496  0.013447   2.0  0.367965  0.209047  0.220146  0.294055


           50%       75%       max
key1
a    -0.394793  0.108805  0.612402
b     0.367965  0.441874  0.515783

[2 rows x 24 columns]

In [164]:
tips=pd.read_csv("tips.csv")

In [165]:
tips.head()

   total_bill   tip smoker  day    time  size
0       16.99  1.01     No  Sun  Dinner     2
1       10.34  1.66     No  Sun  Dinner     3
2       21.01  3.50     No  Sun  Dinner     3
3       23.68  3.31     No  Sun  Dinner     2
4       24.59  3.61     No  Sun  Dinner     4

In [166]:
tips["tip_pct"]=tips["tip"]/tips["total_bill"]

In [167]:
tips.head()

   total_bill   tip smoker  day    time  size   tip_pct
0       16.99  1.01     No  Sun  Dinner     2  0.059447
1       10.34  1.66     No  Sun  Dinner     3  0.160542
2       21.01  3.50     No  Sun  Dinner     3  0.166587
3       23.68  3.31     No  Sun  Dinner     2  0.139780
4       24.59  3.61     No  Sun  Dinner     4  0.146808

In [168]:
grouped=tips.groupby(["day","smoker"])

In [169]:
grouped_pct=grouped["tip_pct"]

In [170]:
grouped_pct.agg("mean")

day   smoker
Fri   No        0.151650
      Yes       0.174783
Sat   No        0.158048
      Yes       0.147906
Sun   No        0.160113
      Yes       0.187250
Thur  No        0.160298
      Yes       0.163863
Name: tip_pct, dtype: float64

In [171]:
grouped_pct.agg(["mean","std",peak_to_peak])

                 mean       std  peak_to_peak
day  smoker
Fri  No      0.151650  0.028123      0.067349
     Yes     0.174783  0.051293      0.159925
Sat  No      0.158048  0.039767      0.235193
     Yes     0.147906  0.061375      0.290095
Sun  No      0.160113  0.042347      0.193226
     Yes     0.187250  0.154134      0.644685
Thur No      0.160298  0.038774      0.193350
     Yes     0.163863  0.039389      0.151240

In [172]:
grouped_pct.agg([("average","mean"),("stdev","std")])

              average     stdev
day  smoker
Fri  No      0.151650  0.028123
     Yes     0.174783  0.051293
Sat  No      0.158048  0.039767
     Yes     0.147906  0.061375
Sun  No      0.160113  0.042347
     Yes     0.187250  0.154134
Thur No      0.160298  0.038774
     Yes     0.163863  0.039389

In [173]:
functions=["count","mean","max"]

In [174]:
result=grouped[["tip_pct","total_bill"]].agg(functions)

In [175]:
result

            tip_pct                     total_bill
              count      mean       max      count       mean    max
day  smoker
Fri  No           4  0.151650  0.187735          4  18.420000  22.75
     Yes         15  0.174783  0.263480         15  16.813333  40.17
Sat  No          45  0.158048  0.291990         45  19.661778  48.33
     Yes         42  0.147906  0.325733         42  21.276667  50.81
Sun  No          57  0.160113  0.252672         57  20.506667  48.17
     Yes         19  0.187250  0.710345         19  24.120000  45.35
Thur No          45  0.160298  0.266312         45  17.113111  41.19
     Yes         17  0.163863  0.241255         17  19.190588  43.11

In [176]:
result["tip_pct"]

             count      mean       max
day  smoker
Fri  No          4  0.151650  0.187735
     Yes        15  0.174783  0.263480
Sat  No         45  0.158048  0.291990
     Yes        42  0.147906  0.325733
Sun  No         57  0.160113  0.252672
     Yes        19  0.187250  0.710345
Thur No         45  0.160298  0.266312
     Yes        17  0.163863  0.241255

In [177]:
ftuples=[("Average","mean"),("Variance","var")]

In [178]:
grouped[["tip_pct","total_bill"]].agg(ftuples)

              tip_pct           total_bill
              Average  Variance    Average    Variance
day  smoker
Fri  No      0.151650  0.000791  18.420000   25.596333
     Yes     0.174783  0.002631  16.813333   82.562438
Sat  No      0.158048  0.001581  19.661778   79.908965
     Yes     0.147906  0.003767  21.276667  101.387535
Sun  No      0.160113  0.001793  20.506667   66.099980
     Yes     0.187250  0.023757  24.120000  109.046044
Thur No      0.160298  0.001503  17.113111   59.625081
     Yes     0.163863  0.001551  19.190588   69.808518

In [179]:
grouped.agg({"tip":"max","size":"sum"})

               tip  size
day  smoker
Fri  No       3.50     9
     Yes      4.73    31
Sat  No       9.00   115
     Yes     10.00   104
Sun  No       6.00   167
     Yes      6.50    49
Thur No       6.70   112
     Yes      5.00    40

In [180]:
grouped.agg({"tip_pct":["min","max","mean","std"],
            "size":"sum"})

              tip_pct                               size
                  min       max      mean       std  sum
day  smoker
Fri  No      0.120385  0.187735  0.151650  0.028123    9
     Yes     0.103555  0.263480  0.174783  0.051293   31
Sat  No      0.056797  0.291990  0.158048  0.039767  115
     Yes     0.035638  0.325733  0.147906  0.061375  104
Sun  No      0.059447  0.252672  0.160113  0.042347  167
     Yes     0.065660  0.710345  0.187250  0.154134   49
Thur No      0.072961  0.266312  0.160298  0.038774  112
     Yes     0.090014  0.241255  0.163863  0.039389   40

In [181]:
tips.groupby(["day","smoker"],as_index=False).mean(numeric_only=True)
#as_index=Falseで階層型インデックスとかになるのを防ぐ

    day smoker  total_bill       tip      size   tip_pct
0   Fri     No   18.420000  2.812500  2.250000  0.151650
1   Fri    Yes   16.813333  2.714000  2.066667  0.174783
2   Sat     No   19.661778  3.102889  2.555556  0.158048
3   Sat    Yes   21.276667  2.875476  2.476190  0.147906
4   Sun     No   20.506667  3.167895  2.929825  0.160113
5   Sun    Yes   24.120000  3.516842  2.578947  0.187250
6  Thur     No   17.113111  2.673778  2.488889  0.160298
7  Thur    Yes   19.190588  3.030000  2.352941  0.163863

In [182]:
def top(df,n=5,column="tip_pct"):
    return df.sort_values(column,ascending=False)[:n]

In [183]:
top(tips,n=6)

     total_bill   tip smoker  day    time  size   tip_pct
172        7.25  5.15    Yes  Sun  Dinner     2  0.710345
178        9.60  4.00    Yes  Sun  Dinner     2  0.416667
67         3.07  1.00    Yes  Sat  Dinner     1  0.325733
232       11.61  3.39     No  Sat  Dinner     2  0.291990
183       23.17  6.50    Yes  Sun  Dinner     4  0.280535
109       14.31  4.00    Yes  Sat  Dinner     2  0.279525

In [184]:
tips.groupby("smoker").apply(top)

C:\Users\sansp\AppData\Local\Temp\ipykernel_36516\2530541573.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  tips.groupby("smoker").apply(top)

            total_bill   tip smoker   day    time  size   tip_pct
smoker
No     232       11.61  3.39     No   Sat  Dinner     2  0.291990
       149        7.51  2.00     No  Thur   Lunch     2  0.266312
       51        10.29  2.60     No   Sun  Dinner     2  0.252672
       185       20.69  5.00     No   Sun  Dinner     5  0.241663
       88        24.71  5.85     No  Thur   Lunch     2  0.236746
Yes    172        7.25  5.15    Yes   Sun  Dinner     2  0.710345
       178        9.60  4.00    Yes   Sun  Dinner     2  0.416667
       67         3.07  1.00    Yes   Sat  Dinner     1  0.325733
       183       23.17  6.50    Yes   Sun  Dinner     4  0.280535
       109       14.31  4.00    Yes   Sat  Dinner     2  0.279525

In [185]:
tips.groupby(["smoker","day"]).apply(top,n=1,column="total_bill")

C:\Users\sansp\AppData\Local\Temp\ipykernel_36516\470388052.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  tips.groupby(["smoker","day"]).apply(top,n=1,column="total_bill")

                 total_bill    tip smoker   day    time  size   tip_pct
smoker day
No     Fri  94        22.75   3.25     No   Fri  Dinner     2  0.142857
       Sat  212       48.33   9.00     No   Sat  Dinner     4  0.186220
       Sun  156       48.17   5.00     No   Sun  Dinner     6  0.103799
       Thur 142       41.19   5.00     No  Thur   Lunch     5  0.121389
Yes    Fri  95        40.17   4.73    Yes   Fri  Dinner     4  0.117750
       Sat  170       50.81  10.00    Yes   Sat  Dinner     3  0.196812
       Sun  182       45.35   3.50    Yes   Sun  Dinner     3  0.077178
       Thur 197       43.11   5.00    Yes  Thur   Lunch     4  0.115982

In [186]:
result=tips.groupby("smoker")["tip_pct"].describe()

In [187]:
result

,count,mean,std,min,25%,50%,75%,max
smoker,,,,,,,,
No,151.0,0.159328,0.039910,0.056797,0.136906,0.155625,0.185014,0.291990
Yes,93.0,0.163196,0.085119,0.035638,0.106771,0.153846,0.195059,0.710345

In [188]:
result.unstack("smoker")

       smoker
count  No        151.000000
       Yes        93.000000
mean   No          0.159328
       Yes         0.163196
std    No          0.039910
       Yes         0.085119
min    No          0.056797
       Yes         0.035638
25%    No          0.136906
       Yes         0.106771
50%    No          0.155625
       Yes         0.153846
75%    No          0.185014
       Yes         0.195059
max    No          0.291990
       Yes         0.710345
dtype: float64

In [189]:
tips.groupby("smoker",group_keys=False).apply(top)
#group_keys=Falseで、グループキーと元のオブジェクトのインデックスの階層型インデックスにするのを無効にする

C:\Users\sansp\AppData\Local\Temp\ipykernel_36516\1024351321.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  tips.groupby("smoker",group_keys=False).apply(top)

     total_bill   tip smoker   day    time  size   tip_pct
232       11.61  3.39     No   Sat  Dinner     2  0.291990
149        7.51  2.00     No  Thur   Lunch     2  0.266312
51        10.29  2.60     No   Sun  Dinner     2  0.252672
185       20.69  5.00     No   Sun  Dinner     5  0.241663
88        24.71  5.85     No  Thur   Lunch     2  0.236746
172        7.25  5.15    Yes   Sun  Dinner     2  0.710345
178        9.60  4.00    Yes   Sun  Dinner     2  0.416667
67         3.07  1.00    Yes   Sat  Dinner     1  0.325733
183       23.17  6.50    Yes   Sun  Dinner     4  0.280535
109       14.31  4.00    Yes   Sat  Dinner     2  0.279525

In [190]:
frame=pd.DataFrame({"data1":np.random.standard_normal(1000),
                   "data2":np.random.standard_normal(1000)})

In [191]:
frame.head()

      data1     data2
0  0.320131 -0.773232
1 -0.061990  2.068140
2 -0.527416 -1.962531
3  0.288015  0.902571
4  0.050002 -0.596420

In [192]:
quartiles=pd.cut(frame["data1"],4)

In [193]:
quartiles.head()

0     (0.235, 1.844]
1    (-1.373, 0.235]
2    (-1.373, 0.235]
3     (0.235, 1.844]
4    (-1.373, 0.235]
Name: data1, dtype: category
Categories (4, interval[float64, right]): [(-2.988, -1.373] < (-1.373, 0.235] < (0.235, 1.844] < (1.844, 3.452]]

In [194]:
def get_stats(group):
    return pd.DataFrame({"min":group.min(),"max":group.max(),
                        "count":group.count(),"mean":group.mean()})

In [195]:
grouped=frame.groupby(quartiles)

C:\Users\sansp\AppData\Local\Temp\ipykernel_36516\38721795.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped=frame.groupby(quartiles)

In [196]:
grouped.apply(get_stats)

                             min       max  count      mean
data1
(-2.988, -1.373] data1 -2.982004 -1.396034     80 -1.873026
                 data2 -1.884954  1.990793     80  0.107849
(-1.373, 0.235]  data1 -1.372367  0.234078    517 -0.477838
                 data2 -2.709791  3.307156    517  0.053929
(0.235, 1.844]   data1  0.239510  1.842268    378  0.849807
                 data2 -3.531181  2.705516    378  0.142013
(1.844, 3.452]   data1  1.849146  3.452486     25  2.295308
                 data2 -2.257219  2.851093     25  0.001705

In [197]:
grouped.agg(["min","max","count","mean"])

                     data1                               data2            \
                       min       max count      mean       min       max
data1
(-2.988, -1.373] -2.982004 -1.396034    80 -1.873026 -1.884954  1.990793
(-1.373, 0.235]  -1.372367  0.234078   517 -0.477838 -2.709791  3.307156
(0.235, 1.844]    0.239510  1.842268   378  0.849807 -3.531181  2.705516
(1.844, 3.452]    1.849146  3.452486    25  2.295308 -2.257219  2.851093


                 count      mean
data1
(-2.988, -1.373]    80  0.107849
(-1.373, 0.235]    517  0.053929
(0.235, 1.844]     378  0.142013
(1.844, 3.452]      25  0.001705

In [199]:
quartiles_smap=pd.qcut(frame["data1"],4,labels=False)

In [200]:
quartiles_smap.head()

0    2
1    1
2    1
3    2
4    2
Name: data1, dtype: int64

In [201]:
grouped=frame.groupby(quartiles_smap)

In [202]:
grouped.apply(get_stats)

                  min       max  count      mean
data1
0     data1 -2.982004 -0.712577    250 -1.268535
      data2 -2.709791  2.793222    250  0.052524
1     data1 -0.707598 -0.015602    250 -0.362184
      data2 -2.645778  3.307156    250  0.029046
2     data1 -0.004537  0.689178    250  0.324393
      data2 -2.331576  2.769244    250  0.148538
3     data1  0.692603  3.452486    250  1.233228
      data2 -3.531181  2.851093    250  0.130822

In [203]:
s=pd.Series(np.random.standard_normal(6))

In [204]:
s[::2]=np.nan

In [205]:
s

0         NaN
1   -0.307746
2         NaN
3    0.342081
4         NaN
5   -0.503634
dtype: float64

In [207]:
s.fillna(s.mean())

0   -0.156433
1   -0.307746
2   -0.156433
3    0.342081
4   -0.156433
5   -0.503634
dtype: float64

In [208]:
states=["Ohio","New York","Vermont","Florida","Oregon","Nevada","California","Idaho"]

In [209]:
group_key=["East","East","East","East","West","West","West","West"]

In [210]:
data=pd.Series(np.random.standard_normal(8),index=states)

In [211]:
data

Ohio         -0.489745
New York      1.556107
Vermont       0.210101
Florida      -0.384870
Oregon        0.149208
Nevada        0.056130
California   -0.560792
Idaho         1.616128
dtype: float64

In [213]:
data[["Vermont","Nevada","Idaho"]]=np.nan

In [214]:
data

Ohio         -0.489745
New York      1.556107
Vermont            NaN
Florida      -0.384870
Oregon        0.149208
Nevada             NaN
California   -0.560792
Idaho              NaN
dtype: float64

In [215]:
data.groupby(group_key).size()

East    4
West    4
dtype: int64

In [216]:
data.groupby(group_key).count()

East    3
West    2
dtype: int64

In [217]:
data.groupby(group_key).mean()

East    0.227164
West   -0.205792
dtype: float64

In [218]:
def fill_mean(group):
    return group.fillna(group.mean())

In [220]:
data.groupby(group_key).apply(fill_mean)

East  Ohio         -0.489745
      New York      1.556107
      Vermont       0.227164
      Florida      -0.384870
West  Oregon        0.149208
      Nevada       -0.205792
      California   -0.560792
      Idaho        -0.205792
dtype: float64

In [221]:
fill_values={"East":0.5,"West":-1}

In [222]:
def fill_func(group):
    return group.fillna(fill_values[group.name])

In [223]:
data.groupby(group_key).apply(fill_func)

East  Ohio         -0.489745
      New York      1.556107
      Vermont       0.500000
      Florida      -0.384870
West  Oregon        0.149208
      Nevada       -1.000000
      California   -0.560792
      Idaho        -1.000000
dtype: float64

In [224]:
suits=["H","S","C","D"]
card_val=(list(range(1,11))+[10]*3)*4
base_names=["A"]+list(range(2,11))+["J","K","Q"]
cards=[]
for suit in suits:
    cards.extend(str(num)+suit for num in base_names)
deck=pd.Series(card_val,index=cards)

In [226]:
deck.head(13)

AH      1
2H      2
3H      3
4H      4
5H      5
6H      6
7H      7
8H      8
9H      9
10H    10
JH     10
KH     10
QH     10
dtype: int64

In [227]:
def draw(deck,n=5):
    return deck.sample(n)

In [228]:
draw(deck)

10H    10
9H      9
3H      3
8D      8
6C      6
dtype: int64

In [229]:
def get_suit(card):
    return card[-1]

In [230]:
deck.groupby(get_suit).apply(draw,n=2)

C  QC    10
   7C     7
D  5D     5
   2D     2
H  JH    10
   4H     4
S  2S     2
   3S     3
dtype: int64

In [231]:
deck.groupby(get_suit,group_keys=False).apply(draw,n=2)

5C    5
8C    8
4D    4
8D    8
2H    2
AH    1
6S    6
3S    3
dtype: int64

In [233]:
df=pd.DataFrame({"category":["a","a","a","a","b","b","b","b"],
                 "data":np.random.standard_normal(8),
                 "weights":np.random.uniform(size=8)})

In [234]:
df

  category      data   weights
0        a  0.162731  0.230406
1        a -0.890980  0.925873
2        a  1.803528  0.206110
3        a  0.587926  0.981833
4        b -0.939447  0.086937
5        b -0.176512  0.260211
6        b -1.614811  0.714490
7        b -1.999933  0.164330

In [235]:
grouped=df.groupby("category")

In [236]:
def get_wavg(group):
    return np.average(group["data"],weights=group["weights"])

In [237]:
grouped.apply(get_wavg)

C:\Users\sansp\AppData\Local\Temp\ipykernel_36516\4286695940.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped.apply(get_wavg)

category
a    0.068906
b   -1.313262
dtype: float64

In [238]:
close_px=pd.read_csv("stock_px.csv",parse_dates=True,index_col=0)

In [239]:
close_px.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2214 entries, 2003-01-02 to 2011-10-14
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AAPL    2214 non-null   float64
 1   MSFT    2214 non-null   float64
 2   XOM     2214 non-null   float64
 3   SPX     2214 non-null   float64
dtypes: float64(4)
memory usage: 86.5 KB

In [240]:
close_px.tail()

              AAPL   MSFT    XOM      SPX
2011-10-10  388.81  26.94  76.28  1194.89
2011-10-11  400.29  27.00  76.27  1195.54
2011-10-12  402.19  26.96  77.16  1207.25
2011-10-13  408.43  27.18  76.37  1203.66
2011-10-14  422.00  27.27  78.11  1224.58

In [241]:
def spx_corr(group):
    return group.corrwith(group["SPX"])

In [242]:
rets=close_px.pct_change().dropna()

In [243]:
def get_year(x):
    return x.year

In [244]:
by_year=rets.groupby(get_year)

In [245]:
by_year.apply(spx_corr)

          AAPL      MSFT       XOM  SPX
2003  0.541124  0.745174  0.661265  1.0
2004  0.374283  0.588531  0.557742  1.0
2005  0.467540  0.562374  0.631010  1.0
2006  0.428267  0.406126  0.518514  1.0
2007  0.508118  0.658770  0.786264  1.0
2008  0.681434  0.804626  0.828303  1.0
2009  0.707103  0.654902  0.797921  1.0
2010  0.710105  0.730118  0.839057  1.0
2011  0.691931  0.800996  0.859975  1.0

In [246]:
def corr_aapl_msft(group):
    return group["AAPL"].corr(group["MSFT"])

In [247]:
by_year.apply(corr_aapl_msft)

2003    0.480868
2004    0.259024
2005    0.300093
2006    0.161735
2007    0.417738
2008    0.611901
2009    0.432738
2010    0.571946
2011    0.581987
dtype: float64

In [249]:
import statsmodels.api as sm

In [250]:
def regress(data,yvar=None,xvars=None):
    Y=data[yvar]
    X=data[xvars]
    X["intercept"]=1
    result=sm.OLS(Y,X).fit()
    return result.params

In [251]:
by_year.apply(regress,yvar="AAPL",xvars=["SPX"])

           SPX  intercept
2003  1.195406   0.000710
2004  1.363463   0.004201
2005  1.766415   0.003246
2006  1.645496   0.000080
2007  1.198761   0.003438
2008  0.968016  -0.001110
2009  0.879103   0.002954
2010  1.052608   0.001261
2011  0.806605   0.001514

In [252]:
df=pd.DataFrame({"key":["a","b","c"]*4,
                "value":np.arange(12.)})

In [253]:
df

   key  value
0    a    0.0
1    b    1.0
2    c    2.0
3    a    3.0
4    b    4.0
5    c    5.0
6    a    6.0
7    b    7.0
8    c    8.0
9    a    9.0
10   b   10.0
11   c   11.0

In [254]:
g=df.groupby("key")["value"]

In [255]:
g.mean()

key
a    4.5
b    5.5
c    6.5
Name: value, dtype: float64

In [256]:
def get_mean(group):
    return group.mean()

In [257]:
g.transform(get_mean)

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [258]:
g.transform("mean")

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [259]:
def times_two(group):
    return group*2

In [260]:
g.transform(times_two)

0      0.0
1      2.0
2      4.0
3      6.0
4      8.0
5     10.0
6     12.0
7     14.0
8     16.0
9     18.0
10    20.0
11    22.0
Name: value, dtype: float64

In [261]:
def get_ranks(group):
    return group.rank(ascending=False)

In [263]:
g.transform(get_ranks)

0     4.0
1     4.0
2     4.0
3     3.0
4     3.0
5     3.0
6     2.0
7     2.0
8     2.0
9     1.0
10    1.0
11    1.0
Name: value, dtype: float64

In [264]:
def normalize(x):
    return (x-x.mean())/x.std()

In [265]:
g.transform(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [266]:
g.apply(normalize)

key
a    0    -1.161895
     3    -0.387298
     6     0.387298
     9     1.161895
b    1    -1.161895
     4    -0.387298
     7     0.387298
     10    1.161895
c    2    -1.161895
     5    -0.387298
     8     0.387298
     11    1.161895
Name: value, dtype: float64

In [267]:
g.transform("mean")

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [268]:
normalized=(df["value"]-g.transform("mean"))/g.transform("std")

In [269]:
normalized

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [270]:
tips.head()

   total_bill   tip smoker  day    time  size   tip_pct
0       16.99  1.01     No  Sun  Dinner     2  0.059447
1       10.34  1.66     No  Sun  Dinner     3  0.160542
2       21.01  3.50     No  Sun  Dinner     3  0.166587
3       23.68  3.31     No  Sun  Dinner     2  0.139780
4       24.59  3.61     No  Sun  Dinner     4  0.146808

In [271]:
tips.pivot_table(index=["day","smoker"],
                values=["size","tip","tip_pct","total_bill"])

                 size       tip   tip_pct  total_bill
day  smoker
Fri  No      2.250000  2.812500  0.151650   18.420000
     Yes     2.066667  2.714000  0.174783   16.813333
Sat  No      2.555556  3.102889  0.158048   19.661778
     Yes     2.476190  2.875476  0.147906   21.276667
Sun  No      2.929825  3.167895  0.160113   20.506667
     Yes     2.578947  3.516842  0.187250   24.120000
Thur No      2.488889  2.673778  0.160298   17.113111
     Yes     2.352941  3.030000  0.163863   19.190588

In [272]:
tips.pivot_table(index=["time","day"],columns="smoker",
                values=["tip_pct","size"])

                 size             tip_pct
smoker             No       Yes        No       Yes
time   day
Dinner Fri   2.000000  2.222222  0.139622  0.165347
       Sat   2.555556  2.476190  0.158048  0.147906
       Sun   2.929825  2.578947  0.160113  0.187250
       Thur  2.000000       NaN  0.159744       NaN
Lunch  Fri   3.000000  1.833333  0.187735  0.188937
       Thur  2.500000  2.352941  0.160311  0.163863

In [273]:
tips.pivot_table(index=["time","day"],columns="smoker",
                values=["tip_pct","size"],margins=True)

                 size                       tip_pct
smoker             No       Yes       All        No       Yes       All
time   day
Dinner Fri   2.000000  2.222222  2.166667  0.139622  0.165347  0.158916
       Sat   2.555556  2.476190  2.517241  0.158048  0.147906  0.153152
       Sun   2.929825  2.578947  2.842105  0.160113  0.187250  0.166897
       Thur  2.000000       NaN  2.000000  0.159744       NaN  0.159744
Lunch  Fri   3.000000  1.833333  2.000000  0.187735  0.188937  0.188765
       Thur  2.500000  2.352941  2.459016  0.160311  0.163863  0.161301
All          2.668874  2.408602  2.569672  0.159328  0.163196  0.160803

In [274]:
tips.pivot_table(index=["time","smoker"],columns="day",
                values="tip_pct",aggfunc=len,margins=True)

day             Fri   Sat   Sun  Thur  All
time   smoker
Dinner No       3.0  45.0  57.0   1.0  106
       Yes      9.0  42.0  19.0   NaN   70
Lunch  No       1.0   NaN   NaN  44.0   45
       Yes      6.0   NaN   NaN  17.0   23
All            19.0  87.0  76.0  62.0  244

In [275]:
tips.pivot_table(index=["time","size","smoker"],columns="day",
                values="tip_pct",fill_value=0)

day                      Fri       Sat       Sun      Thur
time   size smoker
Dinner 1    No      0.000000  0.137931  0.000000  0.000000
            Yes     0.000000  0.325733  0.000000  0.000000
       2    No      0.139622  0.162705  0.168859  0.159744
            Yes     0.171297  0.148668  0.207893  0.000000
       3    No      0.000000  0.154661  0.152663  0.000000
...                      ...       ...       ...       ...
Lunch  3    Yes     0.000000  0.000000  0.000000  0.204952
       4    No      0.000000  0.000000  0.000000  0.138919
            Yes     0.000000  0.000000  0.000000  0.155410
       5    No      0.000000  0.000000  0.000000  0.121389
       6    No      0.000000  0.000000  0.000000  0.173706

[21 rows x 4 columns]

In [276]:
from io import StringIO

In [277]:
data="""Sample Nationality Handedness
1   USA  Right-handed
2   Japan    Left-handed
3   USA  Right-handed
4   Japan    Right-handed
5   Japan    Left-handed
6   Japan    Right-handed
7   USA  Right-handed
8   USA  Left-handed
9   Japan    Right-handed
10  USA  Right-handed"""

In [279]:
data=pd.read_table(StringIO(data),sep="\s+")

In [280]:
data

   Sample Nationality    Handedness
0       1         USA  Right-handed
1       2       Japan   Left-handed
2       3         USA  Right-handed
3       4       Japan  Right-handed
4       5       Japan   Left-handed
5       6       Japan  Right-handed
6       7         USA  Right-handed
7       8         USA   Left-handed
8       9       Japan  Right-handed
9      10         USA  Right-handed

In [282]:
pd.crosstab(data["Nationality"],data["Handedness"],margins=True)

Handedness   Left-handed  Right-handed  All
Nationality
Japan                  2             3    5
USA                    1             4    5
All                    3             7   10

In [283]:
pd.crosstab([tips["time"],tips["day"]],tips["smoker"],margins=True)

smoker        No  Yes  All
time   day
Dinner Fri     3    9   12
       Sat    45   42   87
       Sun    57   19   76
       Thur    1    0    1
Lunch  Fri     1    6    7
       Thur   44   17   61
All          151   93  244