In [3]:
import numpy as np
import pandas as pd
pd.options.display.max_columns=20 #DataFrameの表示の際に、最大20列まで表示
pd.options.display.max_rows=20     #DataFrameの表示の際に、最大20行まで表示
pd.options.display.max_colwidth=80 #1つのセルに表示される文字数を最大80文字に制限
np.set_printoptions(precision=4,suppress=True) #小数点以下4桁まで表示かつ非常に小さい数を指数表記(e-05 とか)にしない

In [4]:
data=pd.DataFrame({"x0":[1,2,3,4,5],
                  "x1":[0.01,-0.01,0.25,-4.1,0.],
                  "y":[-1.5,0.,3.6,1.3,-2.1]})

In [5]:
data

   x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.1

In [6]:
data.columns

Index(['x0', 'x1', 'y'], dtype='object')

In [7]:
data.to_numpy()

array([[ 1.  ,  0.01, -1.5 ],
       [ 2.  , -0.01,  0.  ],
       [ 3.  ,  0.25,  3.6 ],
       [ 4.  , -4.1 ,  1.3 ],
       [ 5.  ,  0.  , -2.1 ]])

In [8]:
df2=pd.DataFrame(data.to_numpy(),columns=["one","two","three"])

In [9]:
df2

   one   two  three
0  1.0  0.01   -1.5
1  2.0 -0.01    0.0
2  3.0  0.25    3.6
3  4.0 -4.10    1.3
4  5.0  0.00   -2.1

In [10]:
df3=data.copy()

In [11]:
df3["strings"]=["a","b","c","d","e"]

In [12]:
df3

   x0    x1    y strings
0   1  0.01 -1.5       a
1   2 -0.01  0.0       b
2   3  0.25  3.6       c
3   4 -4.10  1.3       d
4   5  0.00 -2.1       e

In [13]:
df3.to_numpy()

array([[1, 0.01, -1.5, 'a'],
       [2, -0.01, 0.0, 'b'],
       [3, 0.25, 3.6, 'c'],
       [4, -4.1, 1.3, 'd'],
       [5, 0.0, -2.1, 'e']], dtype=object)

In [14]:
model_cols=["x0","x1"]

In [16]:
data.loc[:,model_cols].to_numpy()

array([[ 1.  ,  0.01],
       [ 2.  , -0.01],
       [ 3.  ,  0.25],
       [ 4.  , -4.1 ],
       [ 5.  ,  0.  ]])

In [17]:
data["category"]=pd.Categorical(["a","b","a","a","b"],
                               categories=["a","b"])

In [18]:
data

   x0    x1    y category
0   1  0.01 -1.5        a
1   2 -0.01  0.0        b
2   3  0.25  3.6        a
3   4 -4.10  1.3        a
4   5  0.00 -2.1        b

In [21]:
dummies=pd.get_dummies(data.category,prefix="category")

In [22]:
data_with_dummies=data.drop("category",axis=1).join(dummies)

In [26]:
data_with_dummies.astype(int)

   x0  x1  y  category_a  category_b
0   1   0 -1           1           0
1   2   0  0           0           1
2   3   0  3           1           0
3   4  -4  1           1           0
4   5   0 -2           0           1

In [27]:
conda install statsmodels

Jupyter detected...
3 channel Terms of Service accepted
Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\sansp\anaconda3

  added / updated specs:
    - statsmodels


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2025.12.2  |       haa95532_0         125 KB
    certifi-2026.01.04         |  py313haa95532_0         148 KB
    ------------------------------------------------------------
                                           Total:         273 KB

The following packages will be UPDATED:

  ca-certificates                       2025.9.9-haa95532_0 --> 2025.12.2-haa95532_0
  certifi                          2025.8.3-py313haa95532_0 --> 2026.01.04-py313haa95532_0



Downloading and Extracting Packages: ...working...
certifi-2026.01.04   | 148 KB    |            |   0%

ca-certificates-2025 | 125 KB    |            |   0%
certifi-2026.01.04   | 148 KB    | #          |  11%

ca-certificates-2025 | 125 KB    | #2         |  13%
certifi-2026.01.04   | 148 KB    | ########## | 100%
certifi-2026.01.04   | 148 KB    | ########## | 100%

ca-certificates-2025 | 125 KB    | ########## | 100%

ca-certificates-2025 | 125 KB    | ########## | 100%

ca-certificates-2025 | 125 KB    | ########## | 100%
certifi-2026.01.04   | 148 KB    | ########## | 100%



                                                      done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.

==> WARNING: A newer version of conda exists. <==
    current version: 25.5.1
    latest version: 26.1.1

Please update conda by running

    $ conda update -n base -c defaults conda

In [28]:
data=pd.DataFrame({"x0":[1,2,3,4,5],
                  "x1":[0.01,-0.01,0.25,-4.1,0.],
                  "y":[-1.5,0.,3.6,1.3,-2.1]})

In [29]:
data

   x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.1

In [30]:
import patsy

In [31]:
y,X=patsy.dmatrices("y~x0+x1",data)

In [32]:
y

DesignMatrix with shape (5, 1)
     y
  -1.5
   0.0
   3.6
   1.3
  -2.1
  Terms:
    'y' (column 0)

In [33]:
X

DesignMatrix with shape (5, 3)
  Intercept  x0     x1
          1   1   0.01
          1   2  -0.01
          1   3   0.25
          1   4  -4.10
          1   5   0.00
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'x1' (column 2)

In [34]:
np.asarray(y)

array([[-1.5],
       [ 0. ],
       [ 3.6],
       [ 1.3],
       [-2.1]])

In [35]:
np.asarray(X)

array([[ 1.  ,  1.  ,  0.01],
       [ 1.  ,  2.  , -0.01],
       [ 1.  ,  3.  ,  0.25],
       [ 1.  ,  4.  , -4.1 ],
       [ 1.  ,  5.  ,  0.  ]])

In [36]:
patsy.dmatrices("y~x0+x1+0",data)[1]

DesignMatrix with shape (5, 2)
  x0     x1
   1   0.01
   2  -0.01
   3   0.25
   4  -4.10
   5   0.00
  Terms:
    'x0' (column 0)
    'x1' (column 1)

In [39]:
coef,resid,_,_=np.linalg.lstsq(X,y)
#左から順に回帰係数、残差平方和、ランク、特異値

In [40]:
coef

array([[ 0.3589],
       [-0.1045],
       [-0.2785]])

In [41]:
y,X=patsy.dmatrices("y~x0+np.log(np.abs(x1)+1)",data)

In [42]:
X

DesignMatrix with shape (5, 3)
  Intercept  x0  np.log(np.abs(x1) + 1)
          1   1                 0.00995
          1   2                 0.00995
          1   3                 0.22314
          1   4                 1.62924
          1   5                 0.00000
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'np.log(np.abs(x1) + 1)' (column 2)

In [45]:
y,X=patsy.dmatrices("y~standardize(x0)+center(x1)",data)
#centerは平均値引いただけ

In [46]:
X

DesignMatrix with shape (5, 3)
  Intercept  standardize(x0)  center(x1)
          1         -1.41421        0.78
          1         -0.70711        0.76
          1          0.00000        1.02
          1          0.70711       -3.33
          1          1.41421        0.77
  Terms:
    'Intercept' (column 0)
    'standardize(x0)' (column 1)
    'center(x1)' (column 2)

In [47]:
new_data=pd.DataFrame({"x0":[6,7,8,9],
                       "x1":[3.1,-0.5,0.,2.3],
                       "y":[1,2,3,4]})

In [48]:
new_X=patsy.build_design_matrices([X.design_info],new_data)

In [49]:
new_X

[DesignMatrix with shape (4, 3)
   Intercept  standardize(x0)  center(x1)
           1          2.12132        3.87
           1          2.82843        0.27
           1          3.53553        0.77
           1          4.24264        3.07
   Terms:
     'Intercept' (column 0)
     'standardize(x0)' (column 1)
     'center(x1)' (column 2)]

In [50]:
y,X=patsy.dmatrices("y~I(x0+x1)",data)

In [51]:
X

DesignMatrix with shape (5, 2)
  Intercept  I(x0 + x1)
          1        1.01
          1        1.99
          1        3.25
          1       -0.10
          1        5.00
  Terms:
    'Intercept' (column 0)
    'I(x0 + x1)' (column 1)

In [53]:
data=pd.DataFrame({"key1":["a","a","b","b","a","b","a","b"],
                   "key2":[0,1,0,1,0,1,0,0],
                   "v1":[1,2,3,4,5,6,7,8],
                   "v2":[-1,0,2.5,-0.5,4.0,-1.2,0.2,-1.7]})

In [55]:
y,X=patsy.dmatrices("v2~key1",data)

In [56]:
X

DesignMatrix with shape (8, 2)
  Intercept  key1[T.b]
          1          0
          1          0
          1          1
          1          1
          1          0
          1          1
          1          0
          1          1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)

In [57]:
y

DesignMatrix with shape (8, 1)
    v2
  -1.0
   0.0
   2.5
  -0.5
   4.0
  -1.2
   0.2
  -1.7
  Terms:
    'v2' (column 0)

In [58]:
y,X=patsy.dmatrices("v2~key1+0",data)

In [59]:
X

DesignMatrix with shape (8, 2)
  key1[a]  key1[b]
        1        0
        1        0
        0        1
        0        1
        1        0
        0        1
        1        0
        0        1
  Terms:
    'key1' (columns 0:2)

In [60]:
y,X=patsy.dmatrices("v2~C(key2)",data)

In [61]:
X

DesignMatrix with shape (8, 2)
  Intercept  C(key2)[T.1]
          1             0
          1             1
          1             0
          1             1
          1             0
          1             1
          1             0
          1             0
  Terms:
    'Intercept' (column 0)
    'C(key2)' (column 1)

In [62]:
data["key2"]=data["key2"].map({0:"zero",1:"one"})

In [63]:
data

  key1  key2  v1   v2
0    a  zero   1 -1.0
1    a   one   2  0.0
2    b  zero   3  2.5
3    b   one   4 -0.5
4    a  zero   5  4.0
5    b   one   6 -1.2
6    a  zero   7  0.2
7    b  zero   8 -1.7

In [64]:
y,X=patsy.dmatrices("v2~key1+key2",data)

In [65]:
X

DesignMatrix with shape (8, 3)
  Intercept  key1[T.b]  key2[T.zero]
          1          0             1
          1          0             0
          1          1             1
          1          1             0
          1          0             1
          1          1             0
          1          0             1
          1          1             1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)
    'key2' (column 2)

In [66]:
y,X=patsy.dmatrices("v2~key1+key2+key1:key2",data)

In [67]:
X

DesignMatrix with shape (8, 4)
  Intercept  key1[T.b]  key2[T.zero]  key1[T.b]:key2[T.zero]
          1          0             1                       0
          1          0             0                       0
          1          1             1                       1
          1          1             0                       0
          1          0             1                       0
          1          1             0                       0
          1          0             1                       0
          1          1             1                       1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)
    'key2' (column 2)
    'key1:key2' (column 3)

In [68]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [70]:
rng=np.random.default_rng(seed=12345)

In [72]:
def dnorm(mean,variance,size=1):
    if isinstance(size,int):
        size=size,
    return mean+np.sqrt(variance)*rng.standard_normal(*size)

In [73]:
N=100
X=np.c_[dnorm(0,0.4,size=N),dnorm(0,0.6,size=N),dnorm(0,0.2,size=N)]
eps=dnorm(0,0.1,size=N)
beta=[0.1,0.3,0.5]

In [74]:
y=np.dot(X,beta)+eps

In [75]:
X[:5]

array([[-0.9005, -0.1894, -1.0279],
       [ 0.7993, -1.546 , -0.3274],
       [-0.5507, -0.1203,  0.3294],
       [-0.1639,  0.824 ,  0.2083],
       [-0.0477, -0.2131, -0.0482]])

In [76]:
y[:5]

array([-0.5995, -0.5885,  0.1856, -0.0075, -0.0154])

In [77]:
X_model=sm.add_constant(X)

In [78]:
X_model[:5]

array([[ 1.    , -0.9005, -0.1894, -1.0279],
       [ 1.    ,  0.7993, -1.546 , -0.3274],
       [ 1.    , -0.5507, -0.1203,  0.3294],
       [ 1.    , -0.1639,  0.824 ,  0.2083],
       [ 1.    , -0.0477, -0.2131, -0.0482]])

In [79]:
model=sm.OLS(y,X)

In [81]:
results=model.fit()

In [82]:
results.params

array([0.0668, 0.268 , 0.4505])

In [83]:
print(result.summary())

                                 OLS Regression Results
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.469
Model:                            OLS   Adj. R-squared (uncentered):              0.452
Method:                 Least Squares   F-statistic:                              28.51
Date:                Sat, 28 Mar 2026   Prob (F-statistic):                    2.66e-13
Time:                        03:45:49   Log-Likelihood:                         -25.611
No. Observations:                 100   AIC:                                      57.22
Df Residuals:                      97   BIC:                                      65.04
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.0668      0.054      1.243      0.217      -0.040       0.174
x2             0.2680      0.042      6.313      0.000       0.184       0.352
x3             0.4505      0.068      6.605      0.000       0.315       0.586
==============================================================================
Omnibus:                        0.435   Durbin-Watson:                   1.869
Prob(Omnibus):                  0.805   Jarque-Bera (JB):                0.301
Skew:                           0.134   Prob(JB):                        0.860
Kurtosis:                       2.995   Cond. No.                         1.64
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [84]:
data=pd.DataFrame(X,columns=["col0","col1","col2"])

In [85]:
data["y"]=y

In [86]:
data[:5]

       col0      col1      col2         y
0 -0.900506 -0.189430 -1.027870 -0.599527
1  0.799252 -1.545984 -0.327397 -0.588454
2 -0.550655 -0.120254  0.329359  0.185634
3 -0.163916  0.824040  0.208275 -0.007477
4 -0.047651 -0.213147 -0.048244 -0.015374

In [87]:
results=smf.ols("y~col0+col1+col2",data=data).fit()

In [88]:
results.params

Intercept   -0.020799
col0         0.065813
col1         0.268970
col2         0.449419
dtype: float64

In [89]:
init_x=4

In [90]:
values=[init_x,init_x]
N=1000

In [92]:
b0=0.8
b1=-0.4
noise=dnorm(0,0.1,N)
for i in range(N):
    new_x=values[-1]*b0+values[-2]*b1+noise[i]
    values.append(new_x)

In [93]:
from statsmodels.tsa.ar_model import AutoReg

In [94]:
MAXLAGS=5

In [95]:
model=AutoReg(values,MAXLAGS)

In [96]:
results=model.fit()

In [97]:
results.params

array([-0.0004,  0.8157, -0.3984, -0.0427,  0.0124, -0.0115])

In [101]:
train=pd.read_csv("train.csv")

In [102]:
test=pd.read_csv("test.csv")

In [103]:
train.head(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [104]:
train.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [105]:
test.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [106]:
impute_value=train["Age"].median()

In [107]:
train["Age"]=train["Age"].fillna(impute_value)

In [108]:
test["Age"]=test["Age"].fillna(impute_value)

In [109]:
train["IsFemale"]=(train["Sex"]=="femail").astype(int)

In [110]:
test["IsFemale"]=(test["Sex"]=="femail").astype(int)

In [111]:
predictors=["Pclass","IsFemale","Age"]

In [113]:
X_train=train[predictors].to_numpy()

In [114]:
X_test=test[predictors].to_numpy()

In [115]:
y_train=train["Survived"].to_numpy()

In [116]:
X_train[:5]

array([[ 3.,  0., 22.],
       [ 1.,  0., 38.],
       [ 3.,  0., 26.],
       [ 1.,  0., 35.],
       [ 3.,  0., 35.]])

In [117]:
y_train[:5]

array([0, 1, 1, 1, 0])

In [118]:
from sklearn.linear_model import LogisticRegression

In [119]:
model=LogisticRegression()

In [120]:
model.fit(X_train,y_train)

LogisticRegression()

In [121]:
y_predict=model.predict(X_test)

In [122]:
y_predict[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [125]:
from sklearn.linear_model import LogisticRegressionCV

In [126]:
model_cv=LogisticRegressionCV(Cs=10)

In [127]:
model_cv.fit(X_train,y_train)

LogisticRegressionCV()

In [129]:
from sklearn.model_selection import cross_val_score

In [130]:
model=LogisticRegression(C=10)

In [131]:
scores=cross_val_score(model,X_train,y_train,cv=4)

In [132]:
scores

array([0.6323, 0.6996, 0.722 , 0.7207])